import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import ast
import os
import seaborn as sns

# Define paths
download_path = "./"
pd.set_option('display.max_columns', None)

# Read the final results
# Ensure you are reading the correct file name generated by the previous script
df = pd.read_csv(os.path.join(download_path, "Final_Comparison_With_Exact_Probabilities.csv"))

# Helper to parse string intervals (e.g., "[0.1, 0.5]")
def parse_interval(s):
    try:
        # If it's already a list/tuple, return it
        if isinstance(s, (list, tuple)):
            return s
        # If it's a string, evaluate it
        if isinstance(s, str):
            return ast.literal_eval(s)
        return [np.nan, np.nan]
    except:
        return [np.nan, np.nan]


# 1. Define Algorithms present in the dataframe
# We check which columns exist to make the script robust
possible_algos = ['Gibbs_Sampling', 'Metropolis_Hastings']
algorithms = [algo for algo in possible_algos if algo in df.columns]

# The column for exact results in the previous script was named "exact_result"
exact_col = 'Exact_Probability'

# 2. Parse Columns
cols_to_parse = algorithms + [exact_col]

for col in cols_to_parse:
    df[col + '_parsed'] = df[col].apply(parse_interval)

# 3. Calculate RMSE and Coverage
for algo in algorithms:
    # Extract Upper and Lower bounds for Exact and Approx
    ex_l = df[exact_col + '_parsed'].apply(lambda x: x[0] if isinstance(x, (list, tuple)) else np.nan)
    ex_u = df[exact_col + '_parsed'].apply(lambda x: x[1] if isinstance(x, (list, tuple)) else np.nan)

    app_l = df[algo + '_parsed'].apply(lambda x: x[0] if isinstance(x, (list, tuple)) else np.nan)
    app_u = df[algo + '_parsed'].apply(lambda x: x[1] if isinstance(x, (list, tuple)) else np.nan)

    # --- RMSE Calculation ---
    # RMSE for intervals: sqrt( ((l_hat - l)^2 + (u_hat - u)^2) / 2 )
    mse = ((app_l - ex_l) ** 2 + (app_u - ex_u) ** 2) / 2
    df[algo + '_RMSE'] = np.sqrt(mse)


    # --- Coverage Calculation ---
    def calc_cov(row):
        ex = row[exact_col + '_parsed']
        app = row[algo + '_parsed']

        if not isinstance(ex, (list, tuple)) or not isinstance(app, (list, tuple)):
            return np.nan

        ex_l, ex_u = ex[0], ex[1]
        app_l, app_u = app[0], app[1]

        ex_len = ex_u - ex_l

        # Intersection of intervals
        int_l = max(ex_l, app_l)
        int_u = min(ex_u, app_u)
        int_len = max(0, int_u - int_l)

        if ex_len > 1e-9:  # if exact interval has width
            return (int_len / ex_len) * 100.0
        else:
            # Exact is a point (width ~ 0)
            # If the point is inside the approx interval, 100% coverage, else 0%
            if app_l <= ex_l and app_u >= ex_u:
                return 100.0
            else:
                return 0.0


    df[algo + '_Coverage'] = df.apply(calc_cov, axis=1)

# # 4. Filters (as requested)
# # Filter where exact lower bound is not 0 AND exact upper bound is not 0
# df = df[
#     (df[exact_col + '_parsed'].apply(lambda x: x[0]) != 0) &
#     (df[exact_col + '_parsed'].apply(lambda x: x[1]) != 0)
#     ]
#
# # Filter where exact is [0, 1] (Uninformative)
# df = df[
#     ~((df[exact_col + '_parsed'].apply(lambda x: x[0]) == 0) &
#       (df[exact_col + '_parsed'].apply(lambda x: x[1]) == 1))
# ]
#
# # Filter where exact is [1, 1] (Certainty) - Optional based on your previous code
# df = df[
#     ~((df[exact_col + '_parsed'].apply(lambda x: x[0]) == 1) &
#       (df[exact_col + '_parsed'].apply(lambda x: x[1]) == 1))
# ]

# ---------------------------------------------------------
# PLOTTING
# ---------------------------------------------------------

# Colors and shifts for plotting
colors = {'EM_Precomp': 'blue', 'Gibbs_Sampling': 'orange', 'Metropolis_Hastings': 'green'}
shifts = {'EM_Precomp': -5, 'Gibbs_Sampling': 0, 'Metropolis_Hastings': 5}

# --- 1. RMSE Plot ---
plt.figure(figsize=(10, 7.5))

agg_rmse = df.groupby('Iteration')[[algo + '_RMSE' for algo in algorithms]].agg(['mean', 'std'])

for algo in algorithms:
    col_name = algo + '_RMSE'
    means = agg_rmse[col_name]['mean']
    stds = agg_rmse[col_name]['std']
    iterations = means.index

    plt.errorbar(iterations + shifts.get(algo, 0), means, label=algo,
                 fmt='-o', color=colors.get(algo, 'black'), capsize=5, elinewidth=1.5)

plt.title('Mean RMSE with Std Error Bars (Filtered)')
plt.xlabel('Iteration')
plt.ylabel('RMSE')
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

# --- 2. Coverage Plot ---
plt.figure(figsize=(10, 7.5))

agg_cov = df.groupby('Iteration')[[algo + '_Coverage' for algo in algorithms]].agg(['mean', 'std'])

for algo in algorithms:
    col_name = algo + '_Coverage'
    means = agg_cov[col_name]['mean']
    stds = agg_cov[col_name]['std']
    iterations = means.index

    plt.errorbar(iterations + shifts.get(algo, 0), means, label=algo,
                 fmt='-o', color=colors.get(algo, 'black'), capsize=5, elinewidth=1.5)

plt.title('Average Coverage Ratio (%) with Std Error Bars (Filtered)')
plt.xlabel('Iteration')
plt.ylabel('Coverage (%)')
plt.legend()
plt.grid(True, alpha=0.3)
plt.show()

# --- 3. Time Plot (NEW) ---
# Check if Time columns exist.
# Note: In the merge step of the previous script, 'Time' might be suffixed if it existed in both
# (e.g., Time_gibbs, Time_mh) or just 'Time' if only one had it.
# Based on the merge logic: final_results = gb.merge(mh, ..., suffixes=('_gibbs', '_mh'))
# We should look for Time_gibbs and Time_mh

plt.figure(figsize=(10, 7.5))

time_cols = []
if 'Time_gibbs' in df.columns: time_cols.append(('Gibbs_Sampling', 'Time_gibbs'))
if 'Time_mh' in df.columns: time_cols.append(('Metropolis_Hastings', 'Time_mh'))
if 'Time' in df.columns and 'EM_Precomp' in df.columns: time_cols.append(
    ('EM_Precomp', 'Time'))  # Assuming EM time is just 'Time' if generated

if time_cols:
    # Aggregate Time by Iteration
    # We want the mean time taken to reach iteration X across all models

    for algo, t_col in time_cols:
        agg_time = df.groupby('Iteration')[t_col].agg(['mean', 'std'])
        means = agg_time['mean']
        stds = agg_time['std']
        iterations = means.index

        plt.errorbar(iterations, means, yerr=stds, label=algo,
                     fmt='-o', color=colors.get(algo, 'black'), capsize=5, elinewidth=1.5)

    plt.title('Cumulative Learning Time (seconds)')
    plt.xlabel('Iteration')
    plt.ylabel('Time (s)')
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.show()
else:
    print("No time columns found to plot.")